-- 코드를 입력하세요
SELECT A.USER_ID, A.NICKNAME, SUM(B.PRICE) AS TOTAL_SALES
FROM USED_GOODS_USER AS A
JOIN USED_GOODS_BOARD AS B
ON A.USER_ID = B.WRITER_ID
WHERE B.STATUS = 'done'
GROUP BY A.USER_ID, A.NICKNAME
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES ASC;