-- 코드를 입력하세요
SELECT T.AUTHOR_ID, C.AUTHOR_NAME, T.CATEGORY, SUM(SALES * PRICE) AS TOTAL_SALES
FROM (SELECT *
       FROM BOOK_SALES AS A
       NATURAL JOIN BOOK AS B
       WHERE DATE_FORMAT(SALES_DATE, '%m') = '01') AS T
INNER JOIN AUTHOR AS C
ON T.AUTHOR_ID = C.AUTHOR_ID
GROUP BY T.AUTHOR_ID, C.AUTHOR_NAME, T.CATEGORY
ORDER BY T.AUTHOR_ID ASC, T.CATEGORY DESC;