-- 코드를 입력하세요
SELECT PRODUCT_ID, PRODUCT_NAME, SUM(TOTAL_PRICE) AS TOTAL_SALES
FROM (
    SELECT P.PRODUCT_ID, p.PRODUCT_NAME, (PRICE * AMOUNT) AS TOTAL_PRICE
    FROM FOOD_PRODUCT AS P
        INNER JOIN FOOD_ORDER AS O ON P.PRODUCT_ID = O.PRODUCT_ID
    WHERE DATE_FORMAT(O.PRODUCE_DATE, '%Y-%m') = '2022-05') AS SUB_TABLE
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC;

