-- 코드를 입력하세요
SELECT DISTINCT(A.CAR_ID)
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS A
JOIN (
    SELECT CAR_ID, CAR_TYPE
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_TYPE = '세단'
) AS B
ON A.CAR_ID = B.CAR_ID
WHERE DATE_FORMAT(START_DATE, '%m') = '10'
ORDER BY A.CAR_ID DESC;