-- 코드를 입력하세요
SELECT A.REST_ID, A.REST_NAME, A.FOOD_TYPE, A.FAVORITES, A.ADDRESS, ROUND(AVG_SCORE, 2) AS SCORE
FROM REST_INFO AS A
JOIN (
    SELECT AVG(REVIEW_SCORE) AS AVG_SCORE, REST_ID
    FROM REST_REVIEW
    GROUP BY REST_ID
    ) AS B
ON A.REST_ID = B.REST_ID
WHERE ADDRESS LIKE '서울%'
ORDER BY SCORE DESC, A.FAVORITES DESC;